/**
 * Complete Pokémon type effectiveness chart.
 *
 * Each entry describes a single type's offensive and defensive matchups:
 *  - strongAgainst  : types this type deals super-effective (2×) damage to
 *  - weakAgainst    : types this type deals not-very-effective (0.5×) damage to
 *  - immuneTo       : types this type's attacks have no effect on (0×)
 *  - resistantTo    : types this type resists when defending (takes 0.5×)
 *  - weakTo         : types this type is weak to when defending (takes 2×)
 *  - immuneFrom     : types this type is completely immune to when defending (takes 0×)
 */
const typeChart = [
  {
    name: 'Normal',
    color: '#A8A77A',
    strongAgainst: [],
    weakAgainst: ['Rock', 'Steel'],
    immuneTo: ['Ghost'],
    resistantTo: [],
    weakTo: ['Fighting'],
    immuneFrom: ['Ghost'],
  },
  {
    name: 'Fire',
    color: '#EE8130',
    strongAgainst: ['Grass', 'Ice', 'Bug', 'Steel'],
    weakAgainst: ['Fire', 'Water', 'Rock', 'Dragon'],
    immuneTo: [],
    resistantTo: ['Fire', 'Grass', 'Ice', 'Bug', 'Steel', 'Fairy'],
    weakTo: ['Water', 'Ground', 'Rock'],
    immuneFrom: [],
  },
  {
    name: 'Water',
    color: '#6390F0',
    strongAgainst: ['Fire', 'Ground', 'Rock'],
    weakAgainst: ['Water', 'Grass', 'Dragon'],
    immuneTo: [],
    resistantTo: ['Fire', 'Water', 'Ice', 'Steel'],
    weakTo: ['Electric', 'Grass'],
    immuneFrom: [],
  },
  {
    name: 'Electric',
    color: '#F7D02C',
    strongAgainst: ['Water', 'Flying'],
    weakAgainst: ['Electric', 'Grass', 'Dragon'],
    immuneTo: ['Ground'],
    resistantTo: ['Electric', 'Flying', 'Steel'],
    weakTo: ['Ground'],
    immuneFrom: [],
  },
  {
    name: 'Grass',
    color: '#7AC74C',
    strongAgainst: ['Water', 'Ground', 'Rock'],
    weakAgainst: ['Fire', 'Grass', 'Poison', 'Flying', 'Bug', 'Dragon', 'Steel'],
    immuneTo: [],
    resistantTo: ['Water', 'Electric', 'Grass', 'Ground'],
    weakTo: ['Fire', 'Ice', 'Poison', 'Flying', 'Bug'],
    immuneFrom: [],
  },
  {
    name: 'Ice',
    color: '#96D9D6',
    strongAgainst: ['Grass', 'Ground', 'Flying', 'Dragon'],
    weakAgainst: ['Fire', 'Water', 'Ice', 'Steel'],
    immuneTo: [],
    resistantTo: ['Ice'],
    weakTo: ['Fire', 'Fighting', 'Rock', 'Steel'],
    immuneFrom: [],
  },
  {
    name: 'Fighting',
    color: '#C22E28',
    strongAgainst: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'],
    weakAgainst: ['Poison', 'Flying', 'Psychic', 'Bug', 'Fairy'],
    immuneTo: ['Ghost'],
    resistantTo: ['Bug', 'Rock', 'Dark'],
    weakTo: ['Flying', 'Psychic', 'Fairy'],
    immuneFrom: [],
  },
  {
    name: 'Poison',
    color: '#A33EA1',
    strongAgainst: ['Grass', 'Fairy'],
    weakAgainst: ['Poison', 'Ground', 'Rock', 'Ghost'],
    immuneTo: ['Steel'],
    resistantTo: ['Fighting', 'Poison', 'Bug', 'Grass', 'Fairy'],
    weakTo: ['Ground', 'Psychic'],
    immuneFrom: [],
  },
  {
    name: 'Ground',
    color: '#E2BF65',
    strongAgainst: ['Fire', 'Electric', 'Poison', 'Rock', 'Steel'],
    weakAgainst: ['Grass', 'Bug'],
    immuneTo: ['Flying'],
    resistantTo: ['Poison', 'Rock'],
    weakTo: ['Water', 'Grass', 'Ice'],
    immuneFrom: ['Electric'],
  },
  {
    name: 'Flying',
    color: '#A98FF3',
    strongAgainst: ['Grass', 'Fighting', 'Bug'],
    weakAgainst: ['Electric', 'Rock', 'Steel'],
    immuneTo: [],
    resistantTo: ['Grass', 'Fighting', 'Bug'],
    weakTo: ['Electric', 'Ice', 'Rock'],
    immuneFrom: ['Ground'],
  },
  {
    name: 'Psychic',
    color: '#F95587',
    strongAgainst: ['Fighting', 'Poison'],
    weakAgainst: ['Psychic', 'Steel'],
    immuneTo: ['Dark'],
    resistantTo: ['Fighting', 'Psychic'],
    weakTo: ['Bug', 'Ghost', 'Dark'],
    immuneFrom: [],
  },
  {
    name: 'Bug',
    color: '#A6B91A',
    strongAgainst: ['Grass', 'Psychic', 'Dark'],
    weakAgainst: ['Fire', 'Fighting', 'Poison', 'Flying', 'Ghost', 'Steel', 'Fairy'],
    immuneTo: [],
    resistantTo: ['Grass', 'Fighting', 'Ground'],
    weakTo: ['Fire', 'Flying', 'Rock'],
    immuneFrom: [],
  },
  {
    name: 'Rock',
    color: '#B6A136',
    strongAgainst: ['Fire', 'Ice', 'Flying', 'Bug'],
    weakAgainst: ['Fighting', 'Ground', 'Steel'],
    immuneTo: [],
    resistantTo: ['Normal', 'Fire', 'Poison', 'Flying'],
    weakTo: ['Water', 'Grass', 'Fighting', 'Ground', 'Steel'],
    immuneFrom: [],
  },
  {
    name: 'Ghost',
    color: '#735797',
    strongAgainst: ['Psychic', 'Ghost'],
    weakAgainst: ['Dark'],
    immuneTo: ['Normal'],
    resistantTo: ['Poison', 'Bug'],
    weakTo: ['Ghost', 'Dark'],
    immuneFrom: ['Normal', 'Fighting'],
  },
  {
    name: 'Dragon',
    color: '#6F35FC',
    strongAgainst: ['Dragon'],
    weakAgainst: ['Steel'],
    immuneTo: ['Fairy'],
    resistantTo: ['Fire', 'Water', 'Electric', 'Grass'],
    weakTo: ['Ice', 'Dragon', 'Fairy'],
    immuneFrom: [],
  },
  {
    name: 'Dark',
    color: '#705746',
    strongAgainst: ['Psychic', 'Ghost'],
    weakAgainst: ['Fighting', 'Dark', 'Fairy'],
    immuneTo: [],
    resistantTo: ['Ghost', 'Dark'],
    weakTo: ['Fighting', 'Bug', 'Fairy'],
    immuneFrom: ['Psychic'],
  },
  {
    name: 'Steel',
    color: '#B7B7CE',
    strongAgainst: ['Ice', 'Rock', 'Fairy'],
    weakAgainst: ['Fire', 'Water', 'Electric', 'Steel'],
    immuneTo: [],
    resistantTo: [
      'Normal', 'Grass', 'Ice', 'Flying', 'Psychic',
      'Bug', 'Rock', 'Dragon', 'Steel', 'Fairy',
    ],
    weakTo: ['Fire', 'Fighting', 'Ground'],
    immuneFrom: ['Poison'],
  },
  {
    name: 'Fairy',
    color: '#D685AD',
    strongAgainst: ['Fighting', 'Dragon', 'Dark'],
    weakAgainst: ['Fire', 'Poison', 'Steel'],
    immuneTo: [],
    resistantTo: ['Fighting', 'Bug', 'Dark'],
    weakTo: ['Poison', 'Steel'],
    immuneFrom: ['Dragon'],
  },
];

export default typeChart;
